# Generated by Django 5.2.17 on 2026-09-20 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'área / dirección',
                'verbose_name_plural': 'áreas / direcciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'dimensión',
                'verbose_name_plural': 'dimensiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_actualizados', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='indicadores.areadireccion')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_creados', to=settings.AUTH_USER_MODEL)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicadores', to='indicadores.dimension')),
            ],
            options={
                'verbose_name': 'indicador',
                'verbose_name_plural': 'indicadores',
                'ordering': ['area__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.PositiveIntegerField()),
                ('fecha_vigencia_desde', models.DateField()),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('formula_calculo', models.TextField()),
                ('tipo_calculo', models.CharField(choices=[('valor_directo', 'Valor directo'), ('razon', 'Razón (num / den)')], max_length=20)),
                ('numerador_descripcion', models.CharField(blank=True, max_length=300)),
                ('numerador_unidad', models.CharField(blank=True, max_length=80)),
                ('denominador_descripcion', models.CharField(blank=True, max_length=300)),
                ('denominador_unidad', models.CharField(blank=True, max_length=80)),
                ('unidad_resultado', models.CharField(blank=True, max_length=40)),
                ('meta_tipo', models.CharField(choices=[('minimo', 'Mínimo'), ('maximo', 'Máximo'), ('rango', 'Rango'), ('sostener', 'Sostener'), ('seguimiento', 'Seguimiento')], max_length=20)),
                ('sentido_mejora', models.CharField(choices=[('ascendente', 'Ascendente (más es mejor)'), ('descendente', 'Descendente (menos es mejor)')], max_length=20)),
                ('fuente_datos', models.CharField(blank=True, max_length=300)),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('objetivo_operativo', models.TextField(blank=True)),
                ('nota_metodologica', models.TextField(blank=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='indicadores.indicador')),
            ],
            options={
                'verbose_name': 'versión de indicador',
                'verbose_name_plural': 'versiones de indicador',
                'ordering': ['indicador', '-version_num'],
            },
        ),
        migrations.CreateModel(
            name='MetaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_min', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('meta_max', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('fecha_inicio_meta', models.DateField()),
                ('fecha_fin_meta', models.DateField()),
                ('indicador_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='indicadores.indicadorversion')),
            ],
            options={
                'verbose_name': 'meta de período',
                'verbose_name_plural': 'metas de período',
                'ordering': ['fecha_inicio_meta'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('nro_periodo', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('label', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'período',
                'verbose_name_plural': 'períodos',
                'ordering': ['fecha_inicio'],
                'constraints': [models.UniqueConstraint(fields=('anio', 'frecuencia', 'nro_periodo'), name='periodo_unico')],
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField()),
                ('numerador_valor', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('denominador_valor', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('valor_calculado', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('conclusion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='publicado', max_length=12)),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
                ('indicador_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='indicadores.indicadorversion')),
                ('usuario_carga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_cargadas', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='indicadores.periodo')),
            ],
            options={
                'verbose_name': 'medición',
                'verbose_name_plural': 'mediciones',
                'ordering': ['periodo__fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='indicadores.areadireccion')),
            ],
            options={
                'verbose_name': 'responsable',
                'verbose_name_plural': 'responsables',
            },
        ),
        migrations.AddField(
            model_name='indicador',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores', to='indicadores.responsable'),
        ),
        migrations.AddConstraint(
            model_name='indicadorversion',
            constraint=models.UniqueConstraint(fields=('indicador', 'version_num'), name='indicador_version_num_unico'),
        ),
        migrations.AddConstraint(
            model_name='indicadorversion',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_vigencia_hasta__isnull', True)), fields=('indicador',), name='una_version_vigente_por_indicador'),
        ),
        migrations.AddConstraint(
            model_name='medicion',
            constraint=models.UniqueConstraint(fields=('indicador_version', 'periodo'), name='medicion_unica_por_periodo'),
        ),
    ]
