# Generated by Django 5.2.17 on 2026-09-20 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='indicadores.areadireccion'),
        ),
        migrations.AddField(
            model_name='usuarioarea',
            name='otorgado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresias_otorgadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuarioarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usuarioarea',
            index=models.Index(fields=['usuario', 'fecha_baja'], name='cuentas_usu_usuario_64145d_idx'),
        ),
    ]
