-- Tablero de indicadores — esquema para un proyecto Supabase NUEVO
-- (no usar el proyecto de compromisos/TIEM).
-- SQL Editor → New query → Run.

create table if not exists cuentas_usuario (
  id bigint generated by default as identity primary key,
  password varchar(128) not null default '',
  last_login timestamptz,
  is_superuser boolean not null default false,
  username varchar(150) not null unique,
  first_name varchar(150) not null default '',
  last_name varchar(150) not null default '',
  is_staff boolean not null default false,
  is_active boolean not null default true,
  date_joined timestamptz not null default now(),
  nombre varchar(200) not null default '',
  email varchar(254) not null unique,
  es_admin_global boolean not null default false
);

create table if not exists indicadores_areadireccion (
  id bigint generated by default as identity primary key,
  nombre varchar(200) not null unique
);

create table if not exists indicadores_dimension (
  id bigint generated by default as identity primary key,
  nombre varchar(200) not null unique
);

create table if not exists indicadores_responsable (
  id bigint generated by default as identity primary key,
  nombre varchar(200) not null,
  correo varchar(254) not null default '',
  telefono varchar(50) not null default '',
  area_id bigint not null references indicadores_areadireccion(id) on delete cascade
);

create table if not exists indicadores_periodo (
  id bigint generated by default as identity primary key,
  anio integer not null,
  frecuencia varchar(20) not null,
  nro_periodo smallint not null,
  fecha_inicio date not null,
  fecha_fin date not null,
  label varchar(80) not null,
  unique (anio, frecuencia, nro_periodo)
);

create table if not exists indicadores_indicador (
  id bigint generated by default as identity primary key,
  nombre varchar(300) not null,
  area_id bigint not null references indicadores_areadireccion(id) on delete cascade,
  area_direccion varchar(200) not null default '',
  dimension_id bigint not null references indicadores_dimension(id),
  responsable_id bigint references indicadores_responsable(id) on delete set null,
  activo boolean not null default true,
  creado_por_id bigint references cuentas_usuario(id) on delete set null,
  fecha_creacion timestamptz not null default now(),
  actualizado_por_id bigint references cuentas_usuario(id) on delete set null,
  fecha_actualizacion timestamptz not null default now()
);

create table if not exists indicadores_indicadorversion (
  id bigint generated by default as identity primary key,
  indicador_id bigint not null references indicadores_indicador(id) on delete cascade,
  version_num integer not null,
  fecha_vigencia_desde date not null,
  fecha_vigencia_hasta date,
  formula_calculo text not null default '',
  tipo_calculo varchar(20) not null,
  numerador_descripcion varchar(300) not null default '',
  numerador_unidad varchar(80) not null default '',
  denominador_descripcion varchar(300) not null default '',
  denominador_unidad varchar(80) not null default '',
  unidad_resultado varchar(40) not null default '',
  meta_tipo varchar(20) not null,
  sentido_mejora varchar(20) not null,
  fuente_datos varchar(300) not null default '',
  frecuencia varchar(20) not null,
  objetivo_operativo text not null default '',
  nota_metodologica text not null default '',
  unique (indicador_id, version_num)
);

create table if not exists indicadores_metaperiodo (
  id bigint generated by default as identity primary key,
  indicador_version_id bigint not null references indicadores_indicadorversion(id) on delete cascade,
  meta_min numeric(14, 4),
  meta_max numeric(14, 4),
  fecha_inicio_meta date not null,
  fecha_fin_meta date not null
);

create table if not exists indicadores_medicion (
  id bigint generated by default as identity primary key,
  indicador_version_id bigint not null references indicadores_indicadorversion(id) on delete cascade,
  periodo_id bigint not null references indicadores_periodo(id),
  fecha_corte date not null,
  numerador_valor numeric(16, 4),
  denominador_valor numeric(16, 4),
  valor_calculado numeric(16, 4),
  es_prueba boolean not null default false,
  conclusion text not null default '',
  estado varchar(12) not null default 'publicado',
  usuario_carga_id bigint references cuentas_usuario(id) on delete set null,
  fecha_carga timestamptz not null default now(),
  unique (indicador_version_id, periodo_id)
);

create table if not exists cuentas_usuarioarea (
  id bigint generated by default as identity primary key,
  rol varchar(20) not null,
  fecha_alta timestamptz not null default now(),
  fecha_baja timestamptz,
  usuario_id bigint not null references cuentas_usuario(id) on delete cascade,
  area_id bigint not null references indicadores_areadireccion(id) on delete cascade,
  otorgado_por_id bigint references cuentas_usuario(id) on delete set null
);

create index if not exists cuentas_usuarioarea_usuario_baja
  on cuentas_usuarioarea (usuario_id, fecha_baja);

create or replace view v_indicadores_base
with (security_invoker = true) as
select
  i.id,
  i.nombre,
  i.area_id,
  i.area_direccion,
  i.dimension_id,
  i.activo,
  d.nombre as dimension_nombre,
  a.nombre as area_nombre,
  v.id as version_id,
  v.tipo_calculo,
  v.unidad_resultado,
  v.meta_tipo,
  v.sentido_mejora,
  v.frecuencia,
  v.formula_calculo,
  v.fuente_datos,
  v.objetivo_operativo
from indicadores_indicador i
join indicadores_dimension d on d.id = i.dimension_id
join indicadores_areadireccion a on a.id = i.area_id
left join indicadores_indicadorversion v
  on v.indicador_id = i.id and v.fecha_vigencia_hasta is null;

alter table cuentas_usuario enable row level security;
alter table cuentas_usuarioarea enable row level security;
alter table indicadores_areadireccion enable row level security;
alter table indicadores_dimension enable row level security;
alter table indicadores_responsable enable row level security;
alter table indicadores_periodo enable row level security;
alter table indicadores_indicador enable row level security;
alter table indicadores_indicadorversion enable row level security;
alter table indicadores_metaperiodo enable row level security;
alter table indicadores_medicion enable row level security;

notify pgrst, 'reload schema';

grant select, insert, update, delete on all tables in schema public to service_role;
grant select on v_indicadores_base to service_role;
grant usage, select on all sequences in schema public to service_role;
